CREATE TABLE quantity_break
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_quantity INT NOT NULL CHECK ( from_quantity > 0 ),
    thru_quantity INT,
    CHECK ( thru_quantity is null or thru_quantity > from_quantity )
);
