CREATE TABLE quantity_break
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_quantity INT NOT NULL CHECK ( from_quantity > 0 ),
    to_quantity   INT,
    CHECK ( to_quantity is null or to_quantity > from_quantity )
);