CREATE TABLE voucher
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50)                         NOT NULL,
    description   VARCHAR(200)                        NOT NULl,
    usage_limit   INT CHECK ( usage_limit > 0 ),
    from_date     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    thru_date     TIMESTAMP,
    created_by_id INT REFERENCES member (id)          NOT NULL,
    CHECK ( thru_date is null or thru_date > from_date )
);

create index idx_voucher_time_range on voucher (from_date, thru_date);