CREATE TABLE product_category
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50)                NOT NULL,
    description   VARCHAR(200)               NOT NULL,
    parent        INT REFERENCES product_category (id),
    created_by_id INT REFERENCES member (id) NOT NULL
);
