CREATE TABLE voucher_distribution
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id          INT REFERENCES voucher (id) NOT NULL,
    member_id           INT REFERENCES member (id)  NOT NULL,
    UNIQUE (voucher_id, member_id)
);
