CREATE DOMAIN price_type AS ENUM
(
    BASE,
    DISCOUNT,
    SURCHARGE
);

CREATE TABLE price_component
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                CHAR(14),
    price_type          price_type                          NOT NULL,
    from_date           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    thru_date           TIMESTAMP,
    description         VARCHAR(200)                        NOT NULL,
    amount              DECIMAL CHECK ( amount is not null or amount > 0 ),
    percentage          DECIMAL(5, 4) CHECK ( percentage is not null or percentage > 0 AND percentage < 1 ),
    product_id          INT REFERENCES product (id),
    product_feature_id  INT REFERENCES product_feature (id),
    product_category_id INT REFERENCES product_category (id),
    quantity_break_id   INT REFERENCES quantity_break (id),
    order_value_id      INT REFERENCES order_value (id),
    restaurant_id       INT REFERENCES restaurant (id),
    membership_id       INT REFERENCES membership (id),
    voucher_id          INT REFERENCES voucher (id),
    vendor_id           INT REFERENCES delivery_vendor (id),
    created_by_id       INT REFERENCES member (id)          NOT NULL,
    CHECK ( (amount IS NULL) != (percentage IS NULL) ),                       -- mutual exclusion
    CHECK ( thru_date is null or thru_date > from_date ),
    CHECK ( coalesce(product_id, product_feature_id, product_category_id, -- at least one condition
                     quantity_break_id, order_value_id, restaurant_id,
                     membership_id, voucher_id, vendor_id) IS NOT NULL ),
    UNIQUE (product_id, product_feature_id, product_category_id, quantity_break_id, order_value_id, restaurant_id,
            membership_id, voucher_id, vendor_id)
);

create index idx_price_time_range on price_component (from_date, thru_date);

create sequence seq_daily_price_index
    start with 1
    increment by 1
    nomaxvalue
    order;

create trigger trg_autogenerate_price_code
    before insert
    on price_component
    for each row
begin
    :new.code := 'PR' || to_char(current_date, 'yyyymmdd') || lpad(seq_daily_price_index.nextval, 4, '0');
end;
/

create procedure reset_daily_price_index as
begin
    execute immediate 'alter sequence seq_daily_price_index restart start with 1;';
end;
/

begin
    DBMS_SCHEDULER.CREATE_JOB(
            job_name => 'periodic_reset_daily_price_index',
            job_type => 'STORED_PROCEDURE',
            job_action => 'SHOPGRAB.RESET_DAILY_PRICE_INDEX',
            start_date => SYSTIMESTAMP,
            repeat_interval => 'FREQ=DAILY;INTERVAL=1;BYHOUR=0',
            enabled => TRUE,
            comments => 'Job that reset the price_component code sequence every day at midnight'
    );
end;
/

create trigger trg_validate_price_component_type
    before insert
    on price_component
    for each row
begin
    if :new.price_type = price_type.BASE
    then
        if coalesce(:new.product_id, :new.product_feature_id) is null or :new.amount is null
        then
            raise_application_error(-20300, 'Base price must be bound to a product or a product feature');
        end if;
    end if;

    if coalesce(:new.product_id, :new.product_feature_id) and :new.order_value_id is not null
    then
        raise_application_error(-20300, 'Order value is not compatible with product or a product feature');
    end if;

    if coalesce(:new.product_id, :new.product_feature_id) and :new.vendor_id is not null
    then
        raise_application_error(-20300, 'Delivery vendor is not compatible with product or a product feature');
    end if;

    if not coalesce(:new.product_id, :new.product_feature_id) and :new.quantity_break_id is not null
    then
        raise_application_error(-20300, 'Quantity break has to be bound with product or a product feature');
    end if;
end;
/



