CREATE TABLE order_item
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   INT REFERENCES orders (id)       NOT NULL,
    product_id INT REFERENCES product (id)      NOT NULL,
    quantity   INT CHECK ( quantity > 0 )       NOT NULL,
    unit_price DECIMAL CHECK ( unit_price > 0 ) NOT NULL,
    remarks    VARCHAR(50)
);