CREATE TABLE feedback
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR2(20),
    order_id      INT REFERENCES orders (id) NOT NULL,
    order_item_id INT REFERENCES order_item (id),
    rating        INT CHECK (rating BETWEEN 1 AND 10),
    content       VARCHAR(300),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP,
    status        VARCHAR(20) DEFAULT 'VISIBLE'
        CHECK (status IN ('VISIBLE', 'HIDDEN', 'REPORTED')),
    UNIQUE (order_id, order_item_id)
);

CREATE OR REPLACE TRIGGER trg_feedback_bi_updated_at
    BEFORE INSERT ON feedback
    FOR EACH ROW
BEGIN
    IF :NEW.updated_at IS NULL THEN
        :NEW.updated_at := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_feedback_bu_updated_at
    BEFORE UPDATE ON feedback
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Sequence 1
CREATE SEQUENCE feedback_seq_daily
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    CYCLE;

-- Trigger 2
CREATE OR REPLACE TRIGGER trg_feedback_generate_code
    BEFORE INSERT ON feedback
    FOR EACH ROW
DECLARE
    v_prefix VARCHAR2(20);
    v_seq    VARCHAR2(4);
BEGIN

    v_prefix := 'FB' || TO_CHAR(SYSDATE, 'DDMMYYYY');

    SELECT LPAD(feedback_seq_daily.NEXTVAL, 4, '0')
    INTO v_seq
    FROM dual;

    :NEW.code := v_prefix || v_seq;

END;
/

CREATE OR REPLACE PROCEDURE reset_daily_feedback_seq AS
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE feedback_seq_daily';
    EXECUTE IMMEDIATE '
    CREATE SEQUENCE feedback_seq_daily
        START WITH 1
        INCREMENT BY 1
        MAXVALUE 9999
        CYCLE';
END;
/

BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
            job_name        => 'JOB_RESET_FEEDBACK_SEQ',
            job_type        => 'STORED_PROCEDURE',
            job_action      => 'RESET_DAILY_FEEDBACK_SEQ',
            start_date      => SYSTIMESTAMP,
            repeat_interval => 'FREQ=DAILY;BYHOUR=0',
            enabled         => TRUE,
            comments        => 'Reset feedback sequence every midnight'
    );
END;
/