CREATE TABLE feedback
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      INT REFERENCES orders (id) NOT NULL,
    order_item_id INT REFERENCES order_item (id),
    rating        INT CHECK (rating BETWEEN 1 AND 10),
    content       VARCHAR(300),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP,
    status        VARCHAR(20) DEFAULT 'VISIBLE'
        CHECK (status IN ('VISIBLE', 'HIDDEN', 'REPORTED')),
    UNIQUE (order_id, order_item_id)
);

CREATE OR REPLACE TRIGGER trg_feedback_bi_updated_at
    BEFORE INSERT ON feedback
    FOR EACH ROW
BEGIN
    IF :NEW.updated_at IS NULL THEN
        :NEW.updated_at := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_feedback_bu_updated_at
    BEFORE UPDATE ON feedback
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/
