CREATE TABLE feedback_image
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_id  INT REFERENCES feedback (id) NOT NULL,
    image_url    VARCHAR(500) NOT NULL,
    uploaded_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);