create or replace function CPAD(text IN VARCHAR, n IN INT, pad IN VARCHAR) return varchar as
begin
    return LPAD(RPAD(text, LENGTH(text) + (n - LENGTH(text)) / 2, pad), n, pad);
end;
/

create or replace function REPEAT(text IN VARCHAR, n IN INT) return varchar as
begin
    return RPAD(text, n, text);
end;
/
CREATE TABLE address
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50) NOT NULL,
    contact_no VARCHAR(15) NOT NULL,
    address_1  VARCHAR(50) NOT NULL,
    address_2  VARCHAR(50),
    address_3  VARCHAR(50),
    city       VARCHAR(50) NOT NULL,
    state      VARCHAR(50) NOT NULL,
    postcode   VARCHAR(10) NOT NULL,
    country    VARCHAR(50) NOT NULl
);
CREATE TABLE delivery_vendor
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(200) NOT NULL
);
CREATE TABLE membership
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)                 NOT NULL,
    description VARCHAR(200)                NOT NULL,
    price       DECIMAL CHECK ( price > 0 ) NOT NULL
);
CREATE TABLE member
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50) UNIQUE                  NOT NULL,
    email      VARCHAR(254) UNIQUE                 NOT NULL, -- max length defined in RFC 3696 https://www.rfc-editor.org/errata_search.php?rfc=3696
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE menu_item_group
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(200) NOT NULL
);
CREATE TABLE order_value
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_amount DECIMAL NOT NULL CHECK ( from_amount > 0 ),
    thru_amount DECIMAL,
    CHECK ( thru_amount is null or thru_amount > from_amount )
);
CREATE TABLE payment_method
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(200) NOT NULL
);
CREATE TABLE quantity_break
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_quantity INT NOT NULL CHECK ( from_quantity > 0 ),
    thru_quantity INT,
    CHECK ( thru_quantity is null or thru_quantity > from_quantity )
);
CREATE TABLE voucher
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50)                         NOT NULL,
    description   VARCHAR(200)                        NOT NULl,
    usage_limit   INT CHECK ( usage_limit > 0 ),
    from_date     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    thru_date     TIMESTAMP,
    created_by_id INT REFERENCES member (id)          NOT NULL,
    CHECK ( thru_date is null or thru_date > from_date )
);

create index idx_voucher_time_range on voucher (from_date, thru_date);
CREATE TABLE member_address
(
    member_id  INT REFERENCES member (id),
    address_id INT REFERENCES address (id) UNIQUE,
    is_primary BOOLEAN DEFAULT FALSE NOT NULL,
    PRIMARY KEY (member_id, address_id)
);

-- TODO: Create trigger for ensuring only one is_primary flag for each member AND automatically assign primary if none
CREATE TABLE payment
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_method_id   INT REFERENCES payment_method (id)  NOT NULl,
    paid_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ref_no              VARCHAR(200)                        NOT NULL,
    amount              DECIMAL CHECK ( amount > 0 )        NOT NULL,
    payment_method_data JSON                                NOT NULL
);
CREATE TABLE product_category
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50)                NOT NULL,
    description   VARCHAR(200)               NOT NULL,
    parent        INT REFERENCES product_category (id),
    created_by_id INT REFERENCES member (id) NOT NULL
);
CREATE TABLE product_feature_group
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50)                     NOT NULL,
    min           INT DEFAULT 0 CHECK ( min >= 0) NOT NULL,
    max           INT,
    created_by_id INT REFERENCES member (id)      NOT NULL,
    CHECK ( max IS NULL OR max >= min )
);
CREATE TABLE product_feature
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50)                NOT NULL,
    code          VARCHAR(200)               NOT NULL,
    created_by_id INT REFERENCES member (id) NOT NULL
);
CREATE TABLE product
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(10) UNIQUE                  NOT NULL,
    name              VARCHAR(50)                         NOT NULL,
    description       VARCHAR(200)                        NOT NULL,
    introduction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    image_url         VARCHAR(2083),
    created_by_id     INT REFERENCES member (id)          NOT NULL
);
CREATE TABLE restaurant
(
    id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                  VARCHAR(10) UNIQUE                  NOT NULL,
    name                  VARCHAR(50)                         NOT NULL,
    description           VARCHAR(200)                        NOT NULL,
    introduction_date     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    image_url             VARCHAR(2083),
    opening_hour          INTERVAL DAY(0) TO SECOND(0)        NOT NULL,
    closing_hour          INTERVAL DAY(0) TO SECOND(0)        NOT NULL,
    is_temporarily_closed BOOLEAN   DEFAULT FALSE             NOT NULL,
    address_id            INT REFERENCES address (id) UNIQUE  NOT NULL,
    created_by_id         INT REFERENCES member (id)          NOT NULL
);
CREATE TABLE voucher_distribution
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id          INT REFERENCES voucher (id) NOT NULL,
    member_id           INT REFERENCES member (id)  NOT NULL
);
CREATE TABLE menu_item
(
    product_id     INT REFERENCES product (id),
    restaurant_id  INT REFERENCES restaurant (id),
    group_id       INT REFERENCES menu_item_group (id),
    is_unavailable BOOLEAN   DEFAULT FALSE             NOT NULL,
    from_date      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    thru_date      TIMESTAMP,
    PRIMARY KEY (product_id, restaurant_id),
    CHECK ( thru_date is null or thru_date > from_date )
);
CREATE TABLE monthly_subscription
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id INT REFERENCES membership (id)      NOT NULL,
    member_id     INT REFERENCES member (id)          NOT NULL,
    from_date     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    thru_date     TIMESTAMP                           NOT NULL,
    CHECK ( thru_date > from_date )
);

-- TODO: trigger to check dont have overlapping membership duration

CREATE SEQUENCE seq_daily_ref_no
    start with 1
    increment by 1
    nomaxvalue
    order;

create trigger trg_autogenerate_ref_no
    before insert
    on payment
    for each row
    begin
        :new.ref_no :='REF' || to_char(current_date, 'yyyymmdd') || lpad(seq_daily_ref_no.nextval, 4, '0');
    end;
/

CREATE OR REPLACE PROCEDURE reset_daily_payment_ref AS
BEGIN

    EXECUTE IMMEDIATE 'ALTER SEQUENCE seq_daily_payment_ref RESTART START WITH 1';
END;
/

BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name        => 'job_reset_payment_ref_daily',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'RESET_DAILY_PAYMENT_REF',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=DAILY;INTERVAL=1;BYHOUR=0',
        enabled         => TRUE,
        comments        => 'Job that reset the payment ref_no sequence every day at midnight'
    );
END;
/
CREATE DOMAIN order_type AS ENUM
(
   DELIVERY,
   PICKUP
);

CREATE TABLE orders
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id     INT REFERENCES member (id)          NOT NULL,
    ordered_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    order_type    order_type                          NOT NULL,
    restaurant_id INT REFERENCES restaurant (id)      NOT NULL
);
CREATE DOMAIN price_type AS ENUM
(
    BASE,
    DISCOUNT,
    SURCHARGE
);

CREATE TABLE price_component
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                CHAR(14),
    price_type          price_type                          NOT NULL,
    from_date           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    thru_date           TIMESTAMP,
    description         VARCHAR(200)                        NOT NULL,
    amount              DECIMAL CHECK ( amount is not null or amount > 0 ),
    percentage          DECIMAL(5, 4) CHECK ( percentage is not null or percentage > 0 AND percentage < 1 ),
    product_id          INT REFERENCES product (id),
    product_feature_id  INT REFERENCES product_feature (id),
    product_category_id INT REFERENCES product_category (id),
    quantity_break_id   INT REFERENCES quantity_break (id),
    order_value_id      INT REFERENCES order_value (id),
    restaurant_id       INT REFERENCES restaurant (id),
    membership_id       INT REFERENCES membership (id),
    voucher_id          INT REFERENCES voucher (id),
    vendor_id           INT REFERENCES delivery_vendor (id),
    created_by_id       INT REFERENCES member (id)          NOT NULL,
    CHECK ( (amount IS NULL) != (percentage IS NULL) ),                       -- mutual exclusion
    CHECK ( thru_date is null or thru_date > from_date ),
    CHECK ( coalesce(product_id, product_feature_id, product_category_id, -- at least one condition
                     quantity_break_id, order_value_id, restaurant_id,
                     membership_id, voucher_id, vendor_id) IS NOT NULL )
);

create index idx_price_time_range on price_component (from_date, thru_date);

create sequence seq_daily_price_index
    start with 1
    increment by 1
    nomaxvalue
    order;

create trigger trg_autogenerate_price_code
    before insert
    on price_component
    for each row
begin
    :new.code := 'PR' || to_char(current_date, 'yyyymmdd') || lpad(seq_daily_price_index.nextval, 4, '0');
end;
/

create procedure reset_daily_price_index as
begin
    execute immediate 'alter sequence seq_daily_price_index restart start with 1;';
end;
/

begin
    DBMS_SCHEDULER.CREATE_JOB(
            job_name => 'periodic_reset_daily_price_index',
            job_type => 'STORED_PROCEDURE',
            job_action => 'SHOPGRAB.RESET_DAILY_PRICE_INDEX',
            start_date => SYSTIMESTAMP,
            repeat_interval => 'FREQ=DAILY;INTERVAL=1;BYHOUR=0',
            enabled => TRUE,
            comments => 'Job that reset the price_component code sequence every day at midnight'
    );
end;
/

create trigger trg_validate_price_component_type
    before insert
    on price_component
    for each row
begin
    if :new.price_type = 1
    then
        if coalesce(:new.product_id, :new.product_feature_id) is null or :new.amount is null
        then
            raise_application_error(-20300, 'Base price must be bound to a product or a product feature');
        end if;
    end if;

    if coalesce(:new.product_id, :new.product_feature_id) is not null and :new.order_value_id is not null
    then
        raise_application_error(-20300, 'Order value is not compatible with product or a product feature');
    end if;

    if coalesce(:new.product_id, :new.product_feature_id) is not null and :new.vendor_id is not null
    then
        raise_application_error(-20300, 'Delivery vendor is not compatible with product or a product feature');
    end if;

    if not coalesce(:new.product_id, :new.product_feature_id) is not null and :new.quantity_break_id is not null
    then
        raise_application_error(-20300, 'Quantity break has to be bound with product or a product feature');
    end if;
end;
/
CREATE TABLE product_attribute
(
    product_id               INT REFERENCES product (id),
    product_feature_group_id INT REFERENCES product_feature_group (id),
    PRIMARY KEY (product_id, product_feature_group_id)
);
CREATE TABLE product_audit (
    audit_id         VARCHAR2(20) PRIMARY KEY, -- eg: PA2603290001
    product_id       INT,
    column_name      VARCHAR2(50),
    old_value        VARCHAR2(500),
    new_value        VARCHAR2(500),
    changed_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    changed_by       VARCHAR2(50)
);

-- Sequence 1 (ID)
CREATE SEQUENCE prod_audit_id_daily START WITH 1 INCREMENT BY 1 MAXVALUE 9999 CYCLE;

-- Trigger
CREATE OR REPLACE TRIGGER trg_product_audit
    AFTER UPDATE ON product
    FOR EACH ROW
DECLARE
    v_audit_prefix VARCHAR2(10);
    v_base_seq     VARCHAR2(4);
    v_counter      NUMBER := 1;
    v_change_count NUMBER := 0;
BEGIN
    v_audit_prefix := 'PA' || TO_CHAR(SYSDATE, 'YYMMDD');

    IF :OLD.name <> :NEW.name THEN
        v_change_count := v_change_count + 1;
    END IF;
    IF :OLD.description <> :NEW.description THEN
        v_change_count := v_change_count + 1;
    END IF;

    BEGIN
        SELECT LPAD(prod_audit_id_daily.NEXTVAL, 4, '0') INTO v_base_seq FROM DUAL;
    EXCEPTION
        WHEN OTHERS THEN
            v_base_seq := '0001';
    END;

    IF :OLD.name <> :NEW.name THEN
        IF v_change_count > 1 THEN
            INSERT INTO product_audit (audit_id, product_id, column_name, old_value, new_value, changed_by)
            VALUES (v_audit_prefix || v_base_seq || LPAD(v_counter, 2, '0'),
                    :OLD.id, 'NAME', :OLD.name, :NEW.name, USER);
        ELSE
            INSERT INTO product_audit (audit_id, product_id, column_name, old_value, new_value, changed_by)
            VALUES (v_audit_prefix || v_base_seq,
                    :OLD.id, 'NAME', :OLD.name, :NEW.name, USER);
        END IF;
        v_counter := v_counter + 1;
    END IF;

    IF :OLD.description <> :NEW.description THEN
        IF v_change_count > 1 THEN
            INSERT INTO product_audit (audit_id, product_id, column_name, old_value, new_value, changed_by)
            VALUES (v_audit_prefix || v_base_seq || LPAD(v_counter, 2, '0'),
                    :OLD.id, 'DESCRIPTION', :OLD.description, :NEW.description, USER);
        ELSE
            INSERT INTO product_audit (audit_id, product_id, column_name, old_value, new_value, changed_by)
            VALUES (v_audit_prefix || v_base_seq,
                    :OLD.id, 'DESCRIPTION', :OLD.description, :NEW.description, USER);
        END IF;
        v_counter := v_counter + 1;
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE reset_daily_product_audit_seq AS
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE prod_audit_id_daily';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE prod_audit_id_daily START WITH 1 INCREMENT BY 1 MAXVALUE 9999 CYCLE';
END;
/

BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
            job_name        => 'JOB_RESET_AUDIT_SEQ_DAILY',
            job_type        => 'STORED_PROCEDURE',
            job_action      => 'RESET_DAILY_PRODUCT_AUDIT_SEQ',
            start_date      => SYSTIMESTAMP,
            repeat_interval => 'FREQ=DAILY;INTERVAL=1;BYHOUR=0',
            enabled         => TRUE,
            comments        => 'Job that resets product audit sequence every day at midnight'
    );
END;
/
CREATE TABLE product_category_classification
(
    product_id          INT REFERENCES product (id),
    product_category_id INT REFERENCES product_category (id),
    from_date           TIMESTAMP             NOT NULL,
    thru_date           TIMESTAMP,
    is_primary          BOOLEAN DEFAULT FALSE NOT NULL,
    PRIMARY KEY (product_id, product_category_id),
    CHECK ( thru_date is null or thru_date > from_date )
);

CREATE INDEX idx_category_classification_dates ON product_category_classification(from_date, thru_date);

-- Create trigger for ensuring only one is_primary flag for each product AND automatically assign primary if none
CREATE OR REPLACE TRIGGER trg_single_primary_category
    FOR INSERT OR UPDATE ON product_category_classification
    COMPOUND TRIGGER

    TYPE product_check_t IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    v_products_to_check product_check_t;
    v_idx PLS_INTEGER := 0;

BEFORE EACH ROW IS
BEGIN
    IF INSERTING AND :NEW.is_primary = FALSE THEN
        DECLARE
            v_has_primary NUMBER;
        BEGIN
            SELECT COUNT(*) INTO v_has_primary
            FROM product_category_classification
            WHERE product_id = :NEW.product_id
              AND is_primary = TRUE
              AND (thru_date IS NULL OR thru_date > CURRENT_TIMESTAMP);

            IF v_has_primary = 0 THEN
                :NEW.is_primary := TRUE;
            END IF;
        END;
    END IF;

    IF :NEW.is_primary = TRUE THEN
        v_idx := v_idx + 1;
        v_products_to_check(v_idx) := :NEW.product_id;
    END IF;

    IF :NEW.from_date IS NULL THEN
        :NEW.from_date := CURRENT_TIMESTAMP;
    END IF;
END BEFORE EACH ROW;

    AFTER STATEMENT IS
        v_primary_count NUMBER;
    BEGIN
        FOR i IN 1..v_idx LOOP
                SELECT COUNT(*) INTO v_primary_count
                FROM product_category_classification
                WHERE product_id = v_products_to_check(i)
                  AND is_primary = TRUE
                  AND (thru_date IS NULL OR thru_date > CURRENT_TIMESTAMP);

                IF v_primary_count > 1 THEN
                    RAISE_APPLICATION_ERROR(-20020,
                                            'Product ' || v_products_to_check(i) || ' has multiple primary categories.');
                END IF;
            END LOOP;
    END AFTER STATEMENT;

    END trg_single_primary_category;
/
CREATE TABLE product_feature_group_field
(
    product_feature_group_id INT REFERENCES product_feature_group (id),
    product_feature_id       INT REFERENCES product_feature (id),
    PRIMARY KEY (product_feature_group_id, product_feature_id)
);

CREATE INDEX idx_feature_group_field_feature ON product_feature_group_field(product_feature_id);
CREATE TABLE delivery
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            INT REFERENCES orders (id) UNIQUE   NOT NULL,
    address_id          INT REFERENCES address (id)         NOT NULL,
    vendor_id           INT REFERENCES delivery_vendor (id) NOT NULL,
    ordered_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estimated_arrive_at TIMESTAMP                           NOT NULL
);
CREATE TABLE invoice
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    INT REFERENCES orders (id) UNIQUE   NOT NULL,
    payment_id  INT REFERENCES payment (id) UNIQUE  NOT NULL,
    invoiced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    amount      DECIMAL CHECK ( amount > 0 )        NOT NULL
);
CREATE TABLE menu_item_audit 
(
    audit_id      VARCHAR2(20) PRIMARY KEY,
    product_id    INT,
    restaurant_id INT,
    column_name   VARCHAR2(50),
    old_value     VARCHAR2(500),
    new_value     VARCHAR2(500),
    changed_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    changed_by    VARCHAR2(50)
);

-- Sequence - 1
CREATE SEQUENCE menu_item_audit_seq_daily
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    CYCLE;

-- Trigger - 2
-- Record any changes made
CREATE OR REPLACE TRIGGER trg_menu_item_audit
    AFTER UPDATE ON menu_item
    FOR EACH ROW
DECLARE
    v_audit_prefix VARCHAR2(10);
    v_base_seq     VARCHAR2(4);
    v_counter      NUMBER := 1;
    v_change_count NUMBER := 0;
BEGIN
    v_audit_prefix := 'MA' || TO_CHAR(SYSDATE, 'YYMMDD');

    -- Count how many fields have been changed
    IF :OLD.is_unavailable <> :NEW.is_unavailable THEN
        v_change_count := v_change_count + 1;
    END IF;

    IF :OLD.from_date <> :NEW.from_date THEN
        v_change_count := v_change_count + 1;
    END IF;

    IF NVL(:OLD.thru_date, TO_TIMESTAMP('1900-01-01','YYYY-MM-DD')) <>
       NVL(:NEW.thru_date, TO_TIMESTAMP('1900-01-01','YYYY-MM-DD')) THEN
        v_change_count := v_change_count + 1;
    END IF;

    -- Get sequence
    BEGIN
        SELECT LPAD(menu_item_audit_seq_daily.NEXTVAL, 4, '0')
        INTO v_base_seq
        FROM DUAL;
    EXCEPTION
        WHEN OTHERS THEN
            v_base_seq := '0001';
    END;

    -- is_unavailable update
    IF :OLD.is_unavailable <> :NEW.is_unavailable THEN
        INSERT INTO menu_item_audit (
            audit_id, product_id, restaurant_id,
            column_name, old_value, new_value, changed_by
        )
        VALUES (
                   v_audit_prefix ||
                   CASE WHEN v_change_count > 1 THEN v_base_seq || LPAD(v_counter,2,'0') ELSE v_base_seq END,
                   :OLD.product_id,
                   :OLD.restaurant_id,
                   'IS_UNAVAILABLE',
                   TO_CHAR(:OLD.is_unavailable),
                   TO_CHAR(:NEW.is_unavailable),
                   USER
               );
        v_counter := v_counter + 1;
    END IF;

    -- from_date update
    IF :OLD.from_date <> :NEW.from_date THEN
        INSERT INTO menu_item_audit (
            audit_id, product_id, restaurant_id,
            column_name, old_value, new_value, changed_by
        )
        VALUES (
                   v_audit_prefix ||
                   CASE WHEN v_change_count > 1 THEN v_base_seq || LPAD(v_counter,2,'0') ELSE v_base_seq END,
                   :OLD.product_id,
                   :OLD.restaurant_id,
                   'FROM_DATE',
                   TO_CHAR(:OLD.from_date, 'YYYY-MM-DD HH24:MI:SS'),
                   TO_CHAR(:NEW.from_date, 'YYYY-MM-DD HH24:MI:SS'),
                   USER
               );
        v_counter := v_counter + 1;
    END IF;

    -- thru_date update
    IF NVL(:OLD.thru_date, TO_TIMESTAMP('1900-01-01','YYYY-MM-DD')) <>
       NVL(:NEW.thru_date, TO_TIMESTAMP('1900-01-01','YYYY-MM-DD')) THEN
        INSERT INTO menu_item_audit (
            audit_id, product_id, restaurant_id,
            column_name, old_value, new_value, changed_by
        )
        VALUES (
                   v_audit_prefix ||
                   CASE WHEN v_change_count > 1 THEN v_base_seq || LPAD(v_counter,2,'0') ELSE v_base_seq END,
                   :OLD.product_id,
                   :OLD.restaurant_id,
                   'THRU_DATE',
                   TO_CHAR(:OLD.thru_date, 'YYYY-MM-DD HH24:MI:SS'),
                   TO_CHAR(:NEW.thru_date, 'YYYY-MM-DD HH24:MI:SS'),
                   USER
               );
        v_counter := v_counter + 1;
    END IF;

END;
/

CREATE OR REPLACE PROCEDURE reset_daily_menu_item_audit_seq AS
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE menu_item_audit_seq_daily';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE menu_item_audit_seq_daily START WITH 1 INCREMENT BY 1 MAXVALUE 9999 CYCLE';
END;
/

BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
            job_name        => 'JOB_RESET_MENU_ITEM_AUDIT_SEQ',
            job_type        => 'STORED_PROCEDURE',
            job_action      => 'RESET_DAILY_MENU_ITEM_AUDIT_SEQ',
            start_date      => SYSTIMESTAMP,
            repeat_interval => 'FREQ=DAILY;INTERVAL=1;BYHOUR=0',
            enabled         => TRUE,
            comments        => 'Reset menu item audit sequence daily at midnight'
    );
END;
/
CREATE TABLE order_item
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   INT REFERENCES orders (id)       NOT NULL,
    product_id INT REFERENCES product (id)      NOT NULL,
    quantity   INT CHECK ( quantity > 0 )       NOT NULL,
    unit_price DECIMAL CHECK ( unit_price > 0 ) NOT NULL,
    remarks    VARCHAR(50)
);
create table subscription_payment
(
    monthly_subscription_id INT REFERENCES monthly_subscription (id),
    payment_id              INT REFERENCES payment (id),
    PRIMARY KEY (monthly_subscription_id, payment_id)
);
CREATE TABLE voucher_redemption
(
    voucher_distribution_id INT REFERENCES voucher_distribution (id) UNIQUE,
    invoice_id              INT REFERENCES invoice (id),
    PRIMARY KEY (voucher_distribution_id, invoice_id)
);

create trigger t_check_voucher_is_available_to_redeem
    before
        insert
    on voucher_redemption
    for each row
declare
    v_voucher_id         voucher.id%type;
    v_within_usage_limit boolean;
    v_within_redeem_time boolean;
    voucher_fully_redeemed exception;
    voucher_redeem_out_of_time exception;
    pragma exception_init ( voucher_fully_redeemed, -4096 );
begin
    begin
        select v.id,
               count(vvr.voucher_distribution_id) < v.usage_limit,
               i.invoiced_at between v.from_date and coalesce(v.thru_date, current_timestamp)
        into v_voucher_id, v_within_usage_limit, v_within_redeem_time
        from voucher_distribution vd
                 join invoice i on i.id = :new.invoice_id
                 join voucher v on vd.voucher_id = v.id
                 left join voucher_distribution vvd on vvd.voucher_id = v.id
                 left join voucher_redemption vvr on vvr.voucher_distribution_id = vvd.id
        where vd.id = :new.voucher_distribution_id
        group by v.id, v.usage_limit, v.from_date, v.thru_date, i.invoiced_at;
    exception
        when no_data_found then
            raise_application_error(-20322, 'Voucher cannot be found');
    end;

    if (v_within_usage_limit = true) then
        raise voucher_fully_redeemed;
    end if;

    if (v_within_redeem_time = false) then
        raise voucher_redeem_out_of_time;
    end if;
exception
    when voucher_fully_redeemed then
        raise_application_error(-20300, 'Voucher fully redeemed');
    when voucher_redeem_out_of_time then
        raise_application_error(-20300, 'Voucher cannot be redeemed out of the available time range');
end;
/

create trigger t_check_voucher_can_change_usage_limit
    before
        update of usage_limit
    on voucher
    for each row
declare
    v_number_of_redeems int;
    voucher_insufficient exception;
    pragma exception_init ( voucher_insufficient, -4096 );
begin
    select count(*)
    into v_number_of_redeems
    from voucher_redemption vr
        join voucher_distribution vd on vd.id = vr.voucher_distribution_id
    where vd.voucher_id = :new.id;

    if (v_number_of_redeems >= :new.usage_limit) then
        raise voucher_insufficient;
    end if;
exception
    when voucher_insufficient then
        raise_application_error(
                -20300,
                'Cannot set limit from ' || :old.usage_limit || ' to ' || :new.usage_limit || ' ' ||
                'when ' || v_number_of_redeems || ' is in use.'
        );
end;
/
CREATE TABLE feedback
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      INT REFERENCES orders (id) NOT NULL,
    order_item_id INT REFERENCES order_item (id),
    rating        INT CHECK (rating BETWEEN 1 AND 10),
    content       VARCHAR(300),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP,
    status        VARCHAR(20) DEFAULT 'VISIBLE'
        CHECK (status IN ('VISIBLE', 'HIDDEN', 'REPORTED')),
    UNIQUE (order_id, order_item_id)
);

CREATE OR REPLACE TRIGGER trg_feedback_bi_updated_at
    BEFORE INSERT ON feedback
    FOR EACH ROW
BEGIN
    IF :NEW.updated_at IS NULL THEN
        :NEW.updated_at := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_feedback_bu_updated_at
    BEFORE UPDATE ON feedback
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/
CREATE DOMAIN adjustment_type AS ENUM
(
    DISCOUNT,
    SURCHARGE,
    SALES_TAX,
    SHIPPING,
    FEE,
    MISCELLANEOUS
);

CREATE TABLE order_item_adjustment
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        INT REFERENCES orders (id) NOT NULL,
    order_item_id   INT REFERENCES order_item (id),
    adjustment_type adjustment_type             NOT NULL,
    amount          DECIMAL CHECK ( amount > 0 ),
    percentage      DECIMAL(5, 4) CHECK ( percentage > 0 AND percentage < 1 ),
    CHECK ( (amount IS NULL) != (percentage IS NULL) )
);
CREATE TABLE order_item_feature
(
    product_feature_id INT REFERENCES product_feature (id),
    order_item_id      INT REFERENCES order_item (id), -- used to denote the order line item the feature is applied to
    quantity           INT CHECK ( quantity > 0 )       NOT NULL,
    unit_price         DECIMAL CHECK ( unit_price >= 0 ) NOT NULL,
    remarks            VARCHAR(50),
    PRIMARY KEY (product_feature_id, order_item_id)
);
CREATE TABLE feedback_image
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_id  INT REFERENCES feedback (id) NOT NULL,
    image_url    VARCHAR(500) NOT NULL,
    uploaded_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

